@rootURl = http://localhost:8000


### signup test api
POST {{rootURl}}/api/auth/signup
Content-Type: application/json

{
    "userName": "Bijay Bhandari",
    "email": "bijaya@email.com",
    "password": "adamghat"
}

### login test api
POST {{rootURl}}/api/auth/login
Content-Type: application/json

{
    "email": "ujit@gmail.com",
    "password": "Adamghat7"
}

### get user listings
GET {{rootURl}}/api/user/listing/689894f5b9c0ee9cb27fb3ef
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk4OTRmNWI5YzBlZTljYjI3ZmIzZWYiLCJpYXQiOjE3NTUyNjY3MTcsImV4cCI6MTc1Nzg1ODcxN30.76wiXKkbEO1oTgRfOAqOnrcrDQ2PQ4ZUTyKOXrPZcm8

### delete user listings
DELETE {{rootURl}}/api/listing/delete/689f385df98f6b97b9762385
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk4OTRmNWI5YzBlZTljYjI3ZmIzZWYiLCJpYXQiOjE3NTUyNjY3MTcsImV4cCI6MTc1Nzg1ODcxN30.76wiXKkbEO1oTgRfOAqOnrcrDQ2PQ4ZUTyKOXrPZcm8