@rootURl = http://localhost:8000


### signup test api
POST {{rootURl}}/api/auth/signup
Content-Type: application/json

{
    "userName": "Bijay Bhandari",
    "email": "bijaya@email.com",
    "password": "adamghat"
}

### login test api
POST {{rootURl}}/api/auth/login
Content-Type: application/json

{
    "email": "ujit@gmail.com",
    "password": "Adamghat7"
}